### ISSUE TITLE
Failed assertion while restarting with copied data

### ISSUE THREAD

**Issue by dvogel** [mediastandardstrust/superfastmatch#3]
I moved a data/ dir from another instance of sfm to this one and started the server back up and after a while it fails an assertion. Here's a gdb backtrace:

```
2012-03-16T16:36:51.479733-05:00: [DEBUG]: Adding Document(6,4814) Slots: 0:0 1:1 2:1 3:1  Total: 3
2012-03-16T16:36:51.479857-05:00: [DEBUG]: Adding Document(6,4815) Slots: 0:1 1:1 2:2 3:1  Total: 5
2012-03-16T16:36:51.479964-05:00: [DEBUG]: Adding Document(6,4816) Slots: 0:1 1:2 2:2 3:2  Total: 7
2012-03-16T16:36:51.480015-05:00: [DEBUG]: Adding Document(6,4817) Slots: 0:2 1:3 2:3 3:3  Total: 11
2012-03-16T16:36:51.480118-05:00: [DEBUG]: Adding Document(6,4818) Slots: 0:3 1:4 2:4 3:4  Total: 15
2012-03-16T16:36:51.480180-05:00: [DEBUG]: Adding Document(6,4819) Slots: 0:4 1:5 2:5 3:5  Total: 19
2012-03-16T16:36:51.480295-05:00: [DEBUG]: Adding Document(6,4820) Slots: 0:4 1:6 2:6 3:6  Total: 22
2012-03-16T16:36:51.480505-05:00: [DEBUG]: Adding Document(6,4821) Slots: 0:5 1:7 2:7 3:7  Total: 26
2012-03-16T16:36:51.480612-05:00: [DEBUG]: Adding Document(6,4822) Slots: 0:6 1:8 2:8 3:8  Total: 30
2012-03-16T16:36:51.480721-05:00: [DEBUG]: Adding Document(6,4823) Slots: 0:6 1:9 2:9 3:9  Total: 33
2012-03-16T16:36:51.480806-05:00: [DEBUG]: Adding Document(6,4824) Slots: 0:7 1:10 2:10 3:10  Total: 37
[Thread 0x7fff6e324700 (LWP 18447) exited]
[New Thread 0x7fff6e324700 (LWP 20109)]
[Thread 0x7fff6db23700 (LWP 18448) exited]
[New Thread 0x7fff6db23700 (LWP 20110)]
[Thread 0x7fff6cdcc700 (LWP 18452) exited]
[New Thread 0x7fff6cdcc700 (LWP 20111)]
[Thread 0x7fff67aa9700 (LWP 18454) exited]
[New Thread 0x7fff67aa9700 (LWP 20112)]
2012-03-16T16:36:51.514864-05:00: [DEBUG]: Posting initialisation finished in: 41.2759 secs
superfastmatch: src/command.cc:131: std::string& superfastmatch::Command::getPayload(): Assertion `registry_->getPayloadDB()->get(toString(payload_id_),payload_)' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff65aa5700 (LWP 18458)]
0x00007ffff6771165 in raise () from /lib/libc.so.6
(gdb) bt
#0  0x00007ffff6771165 in raise () from /lib/libc.so.6
#1  0x00007ffff6773f70 in abort () from /lib/libc.so.6
#2  0x00007ffff676a2b1 in __assert_fail () from /lib/libc.so.6
#3  0x00000000004d98c7 in superfastmatch::Command::getPayload (this=0x7fff28df3110) at src/command.cc:131
#4  0x00000000004d9d3d in superfastmatch::Command::addDocument (this=0x47f4) at src/command.cc:87
#5  0x00000000004d9678 in superfastmatch::Command::execute (this=0x7fff28df3110) at src/command.cc:81
#6  0x00000000004330d1 in superfastmatch::QueueManager::processQueue (this=0xcd2130) at src/queue.cc:44
#7  0x000000000042a195 in superfastmatch::Worker::process_timer (this=0x7fffffffe0e0, serv=<value optimized out>) at src/worker.cc:117
#8  0x00000000004fed76 in kyototycoon::ThreadedServer::TaskQueueImpl::do_task(kyotocabinet::TaskQueue::Task*) ()
#9  0x000000000043a92a in kyotocabinet::TaskQueue::WorkerThread::run (this=0x177dd58) at /usr/local/include/kcthread.h:1264
#10 0x00007ffff71d21ba in kyotocabinet::threadrun(void*) () from /usr/local/lib/libkyotocabinet.so.16
#11 0x00007ffff769e8ba in start_thread () from /lib/libpthread.so.0
#12 0x00007ffff680e02d in clone () from /lib/libc.so.6
#13 0x0000000000000000 in ?? ()
```

Let me know if you would like a copy of the data dir or a core dump.

**Comment by donovanhide** [comment]
Hi Drew,

thanks for that! Did you shut down the SFM instance that you copied from before moving the data directory? Looks like the payload, ie. form data for the POST when the document was originally added is missing.  This might have happened if you started copying/moving while a scraper was halfway through adding a document?

I know assertions aren't great, would you prefer the document add task to be marked as failed when this happens? Atomic adds are what's needed really, but it's a bit tricky across different key value stores...

Separate news is that the directed associations and search is very close and the API is fully documented!! Will push very soon.

Cheers,
Donny.

**Comment by dvogel** [comment]
Yeah, I had shut down the SFM process before copying the data dir, so the data stores should have been consistent. The process on the new server runs for quite a while before hitting that assertion. If the process just failed the insertion rather than bringing down the process, at least it could be retried and the rest of the operation would not be affected.
